export const SET_MAIN_WALLET_SCENE_ID = 'SET_MAIN_WALLET_SCENE_ID'

export const TRACK_WALLET_SCENE_ID = 'TRACK_WALLET_SCENE_ID'

export const UNTRACK_WALLET_SCENE_ID = 'UNTRACK_WALLET_SCENE_ID'

export const SHYFT_SDK = 'SHYFT_SDK'

export const WALLET_SETTINGS = 'WALLET_SETTINGS'

export const SUBSCRIPTION_SOL_AMOUNT = 0.2
